apiVersion: v1
kind: ConfigMap
metadata:
  name: sim-config
  namespace: grid-system
data:
  config.yaml: |
    port: 8000
    model: "llmd-sim-model"
    served-model-name: ["llmd-sim-model"]
    mode: "echo"
    max-num-seqs: 8
    max-waiting-queue-length: 16
    enable-kvcache: true
    kv-cache-size: 256
    block-size: 16
    time-to-first-token: "50ms"
    inter-token-latency: "10ms"
    fake-metrics:
      waiting-requests: "rampreset:0:16:120s"
      kv-cache-usage: "rampreset:0.10:0.90:120s"
    fake-metrics-refresh-interval: "1s"
